### ISSUE TITLE
Could you provide the data partition steps in detail?

### ISSUE THREAD

**Issue by ms-keliu** [pulselabteam/PulseDB#10]
We want to learn more about data partition strategy, but couldn't find how info.mat was generated on PulseDB github. (Generate_Subsets.m only provides how to generate subset based on giving info.mat).  We have read 2.6 in the paper, but kind of confused.
Could you provide the info generation scripts in detail?
Looking forward to your reply. Thanks a lot.

**Comment by WeinanWang-RU** [comment]
Hello:
The data partition operate on some rawer form of data. We do not plan to release them since they are intermediate results generated for producing the reported PulseDB. Including them will increase the already-tight storage burden, and make it hard to keep those already released code organized.

Could you please let me know the specific part that have confused you?

Thanks.

**Comment by ms-keliu** [comment]
First, below are the steps to my understanding, could you please give your comments?

1. Generate AAMI testing set
2. Generate AAMI calibration testing set(the same subjects as 1., excluding segments from 1.)
3. Exclude subjects from 1.and 2.
4. Generate calibration-free testing set(10% randomly-selected subjects of 3.)
5. Exclude subjects from 4.
6. Generate calibration-based testing set(10% of each subject of 5.)
7. Generate training set(90% of each subject of 5.)

For AAMI testing set, how was the number of segments of each subjects determined? 
Was AAMI testing set generated as large as possible? 

Thanks.

**Comment by WeinanWang-RU** [comment]
Hi:
Yes, all your understandings are very correct. 

The primary objective to generate the AAMI testing set is to meet all requirements listed in Table 2, so unlike the random sampling procedures of generating the other subsets, the AAMI testing set is more of manually selected. For PulseDB, since we also need a supplementary dataset from only VitalDB that also fulfills the AAMI requirement, what we are actually doing is to generate AAMI testing set individually for MIMIC and VitalDB subjects (so the supplementary AAMI testing set with only VitalDB subjects can also fulfills all the requirements), then merge them together to form the AAMI testing set in Table 2. 

For MIMIC/VitalDB, since the requirements are to have >85 subjects, each subject with >3 measurements, >5% measurements with SBP>160, >5% measurements with SBP<100, >20% measurements with SBP>140, >5% measurements with DBP>100, >5% measurements with DBP<60, >20% measurements with DBP>85, our starting point is to have 100 subjects from MIMIC/VitalDB, each with 5 segments (measurements), and do trials and errors and adjustments. 

Generally, we start from having 15 subjects with SBP>160, 15 subjects with SBP<100, 20 subjects with SBP>140, 15 subjects with DBP>100, 15 subjects with DBP<60 and 20 subjects with DBP>85. Note the excessive amount of subjects needed for the very high and low SBP and DBP values. This is because, say that you are selecting subjects with SBP>160 to fulfill the >5% ratio requirement, you face that the DBP value from these subjects could impact the ratio of DBP>85 or DBP<60 measurements you have in the dataset, and the same situation happens when you select for the DBP. So generally, you would need additional ratio of these measurements. 

The AAMI testing set is not generated as large as possible, but just to be sufficient to meet the requirements.

Thanks.

**Comment by ms-keliu** [comment]
Thank you very much for your detailed explanation. And I have two more questions: 

1. What is the difference between "AAMI testing set" and "AAMI calibration testing set"?  
2. Whether is it proper to say that AAMI set is more typical of population from medical view, and calibration-based set is more sampling-balanced from statistical view?

**Comment by WeinanWang-RU** [comment]
1. The AAMI calibration set (it's not a "calibration testing set") provide you with different segments from the same subjects in the AAMI testing set as calibration data. Say that you are training on the training set and testing on the AAMI testing set. From Table 4, you see that they belong to different subject groups, so that will be a calibration-free testing. However, you may want to do calibration-based testing, especially given that the AAMI testing set contains mostly extreme BP values. So you can use the AAMI calibration set to let you model have access to some different data from the same group of subjects in the AAMI testing set, while avoiding direct data leakage (that is, avoid touching the segments in the AAMI testing set)
2. I would say that the calibration-based testing set is more to compare with the calibration-free testing set, with respect to the problem that we stated in the paper. You see that both calibration-based and calibration-free testing sets have very close SBP and DBP distribution with the training set, which, from a general deep learning perspective, should give you good testing results, while what you actually see is that the model generalize on one set while overfit on the other. As for the AAMI testing set, it is built to highlight the full requirements of AAMI testing, given that a range of previous studies claim to fulfill AAMI standards while not generating a dataset that complies with all these requirements.

**Comment by ms-keliu** [comment]
Very clear and detailed explanation! Thank you very much for your time and patience. I've learned a lot from your reply :)
