### ISSUE TITLE
How was ECG-ABP alignment ensured?

### ISSUE THREAD

**Issue by amsinha9** [pulselabteam/PulseDB#6]
How were the ECG and ABP data aligned? In the PulseDB paper, it discusses PPG-ABP alignment: (1) "PPG-ABP correlation analysis: The PPG and the ABP signals are first aligned using a lag that yields the highest cross correlation between the two signals to compensate the phase difference of the two signals and the inter-signal misalignment in the MIMIC-III database ([16](https://www.frontiersin.org/articles/10.3389/fdgth.2022.1090854/full#B16), [39](https://www.frontiersin.org/articles/10.3389/fdgth.2022.1090854/full#B39)). Next, the Pearson’s correlation coefficient between the aligned signals is calculated, and the segment is rejected if the correlation coefficient is <0.9..." (2) "ABP Lag, PPG ABP Corr: ABP Lag is the lag that yields the highest cross correlation between ABP F and PPG F. The maximum possible lag is limited to ± 125 samples, or ±1 s. The value of Pearson’s correlation coefficient between ABP F and PPG F aligned using this lag is PPG ABP Corr."

Finally, the paper states, "we suggest using segments from VitalDB for the analysis requiring precise inter-signal alignment among ECG, PPG or ABP." How was precise inter-signal alignment ensured between ECG and ABP?

Thank you for your time. I look forward to hearing from you soon.

**Comment by WeinanWang-RU** [comment]
Hello:
In PulseDB, one criterion we used to include only high quality segments of signals is to ensure that the PPG and the ABP signals have high correlation. However, calculating this correlation directly does not work, because:

- The MIMIC dataset has [inter-waveform misalignment](https://physionet.org/content/mimic3wdb/1.0/). 
- There is a phase difference between the PPG and the ABP signals, even if they have been recorded with perfect synchronization and no inter-waveform misalignment, because PPG and ABP were taken from different positions. 

The first part you quoted describes how we compensate these two issues by applying a compensative lag between the PPG and the ABP signals before calculating their correlation. However, in the PulseDB dataset that you see in this repository:
- the signals we included in PulseDB were the "original" signals with no alignment/lag/compensation applied, because this type of alignment is not always mandatory or necessary across all possible usages of these signals.
- but we did record and include the compensative lag we used when we calculate the PPG-ABP correlation, which is what you have quoted

For the second part that you quoted, we simply implies that unlike MIMIC, there is no inter-waveform misalignment in VitalDB, because they stated that their waveform tracks are [time-synchronized](https://www.nature.com/articles/s41597-022-01411-5).
