### ISSUE TITLE
Subset Statistical information / Distributions

### ISSUE THREAD

**Issue by JoAllg** [pulselabteam/PulseDB#8]
In the Paper you report statistical information on the whole PulseDB dataset. And in your paper "Demographic Information Fusion Using Attentive Pooling In CNN-GRU Model For Systolic Blood Pressure Estimation" I have seen information on two VitalDB subsets, though not on the other subsets..

I just noticed that patient_ids are still included in the subsets, so I can calculate the statistical information myself.

It would still be helpful for others to know the statistical information on all of the subsets. Could you provide them and possibly the code used too?

**Comment by WeinanWang-RU** [comment]
Statistical information of the 5 primary subsets of PulseDB are included in Table 4 of the PulseDB paper. These subsets includes data from both MIMIC and VitalDB subjects.
There are also 5 supplementary subsets, which are the part of data in each of the primary subsets that comes from only VitalDB subjects for the sake of ECG-PPG synchronization and completeness of demographic information, and 2 of them are used in the "Demographic Information Fusion" paper.
Since the supplementary subsets are introduced in Section 4.3 (Limitations) of the PulseDB paper, we only displayed the statistical information of the primary subsets in the PulseDB paper to reduce confusion.

**Comment by JoAllg** [comment]
Understandable that there was no place in the papers to show all statistical information.
I have computed the information for the VitalDB Subsets and can share them here: [vitalDB_Subset_statistics.txt](https://github.com/pulselabteam/PulseDB/files/12303657/vitalDB_Subset_statistics.txt)
Note that where two values are given they describe mean and SDE and that "mean_num_segments-per-subject" does not necessarily mean that each subject has this of segments in the AAMI subsets.
